apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ticket-demo
  region: ap-south-1

managedNodeGroups:
  - name: ng-1
    labels: { role: workers }
    instanceType: t2.medium
    minSize: 3
    maxSize: 6
    desiredCapacity: 3
    volumeSize: 80
    volumeEncrypted: true
    privateNetworking: true
    ssh:
      publicKeyName: ticket_demo
  - name: ng-2
    labels: { role: workers }
    instanceType: m5.xlarge
    minSize: 3
    maxSize: 6
    desiredCapacity: 3
    volumeSize: 80
    volumeEncrypted: true
    privateNetworking: true
    ssh:
      publicKeyName: ticket_demo 

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]
    logRetentionInDays: 7


