apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: inventory
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: inventory
  replicas: 1
  template:
     metadata:
       labels:
         app.kubernetes.io/name: inventory 
     spec:
      serviceAccountName: demo
      containers:
        - name: inventory
          image: 902812008909.dkr.ecr.ap-south-1.amazonaws.com/inventory:main
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: inventory
                  # resources:
                  # limits:
                  # memory: "128Mi"
                  #cpu: "64"

