apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo
  name: orders
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orders
  replicas: 1
  template:
     metadata:
       labels:
         app.kubernetes.io/name: orders
     spec:
      serviceAccountName: demo
      containers:
        - name: orders
          image: 902812008909.dkr.ecr.ap-south-1.amazonaws.com/orders:main 
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: orders
                  # resources:
                  #limits:
                  #memory: "128Mi"
                  #cpu: "64"
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo
  name: orders
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: orders
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: demo
  name: orders
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/group.name: orders
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /ping
    alb.ingress.kubernetes.io/healthcheck-interval-seconds: '30'
    alb.ingress.kubernetes.io/success-codes: '200'
spec:
  rules:
    - http:
        paths:
          - path: /ecom/orders
            pathType: ImplementationSpecific
            backend:
              service:
                name: orders
                port:
                  number: 80


